version: "3.8"
services:
  mongo-db:
    image: mongo:6.0
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017" # localhost:27017 # localhost:27017
    networks:
      - default
    volumes:
      - mongo-db:/data
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  orion:
    image: quay.io/fiware/orion:3.11.0
    hostname: orion
    container_name: fiware-orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    networks:
      - default
    command: -dbhost mongo-db -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
      interval: 5s
  kurento:
    image: kurento/kurento-media-server:6.16.0
    ports:
      - "8888:8888/tcp"
      - "5000-5049:5000-5049/udp"
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5049
  draco:
    image: quay.io/fiware/draco:2.1.0
    hostname: draco
    container_name: fiware-draco
    networks:
      - default
    environment:
      - NIFI_WEB_HTTP_PORT=9091
    expose:
      - "5050"
      - "9091"
    ports:
      - "9091:9091" # localhost:9091
      - "5050:5050"
    healthcheck:
      test: curl --fail -s http://draco:9091/nifi-api/system-diagnostics || exit 1
      start_period: 1m
  perseo-core:
    image: telefonicaiot/perseo-core
    environment:
      - PERSEO_FE_URL=http://perseo-fe:9090
      - MAX_AGE=6000
    networks:
        - default
    depends_on:
      - mongo-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  perseo-fe:
    image: telefonicaiot/perseo-fe
    networks:
      - default
    ports:
      - 9090:9090
    depends_on:
      - perseo-core
    environment:
      - PERSEO_MONGO_ENDPOINT=mongo-db
      - PERSEO_CORE_URL=http://perseo-core:8080
      - PERSEO_LOG_LEVEL=debug
      - PERSEO_ORION_URL=http://orion:1026/
      - PERSEO_SMTP_HOST=www.hostname.com
      - PERSEO_SMTP_PORT=25
      - PERSEO_SMTP_SECURE=false
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.100.0/24

volumes:
  mongo-db: ~

