/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package player;

public class Plate{
  private String plate_number;

  public Plate(String plate_number) {
    this.plate_number = plate_number;
  }


  public String getPlate_number() {
    return plate_number;
  }

  public void setPlate_number(String plate_number) {
    this.plate_number = plate_number;
  }

  
  
}